### ISSUE TITLE
Error while running in docker

### ISSUE THREAD

**Issue by tejaswankalluri** [abinpaul1/BookMyShow-ticket-notifier-telegram-bot#1]
![image](https://user-images.githubusercontent.com/49343044/161303083-7195ba20-0773-4d72-a4d4-42d5402f68a8.png)

**Comment by abinpaul1** [comment]
Did you export the variables before running
```
export TELOXIDE_TOKEN=<Token from BotFather>
export BMS_APP_VERSION=9.7.0
```

The warning in the image attached shows it is not set

**Comment by tejaswankalluri** [comment]
@abinpaul1 how to export these keys
`export TELOXIDE_TOKEN=<Token from BotFather>
export BMS_APP_VERSION=9.7.0`
This is not working for docker I have exported before running docker-compose up

**Comment by tejaswankalluri** [comment]
![image](https://user-images.githubusercontent.com/49343044/165124854-dc6335df-6831-4bc8-afad-aa2014a1ea39.png)

###  for docker its not running but for normal command its running

**Comment by abinpaul1** [comment]
Can you do `docker-compose up` and let me know how it goes.
Also please attach output of `env | grep TELOXIDE` and `env | grep BMS` from the shell you are running the commands from.

**Comment by abinpaul1** [comment]
As a workaround you could also hardcode your values in the `docker-compose.yml` file. Change the `${TELOXIDE_TOKEN}` and `${BMS_APP_VERSION}` to your values and try proceeding.

**Comment by tejaswankalluri** [comment]
Yes, now its working thanks.

**Comment by abinpaul1** [comment]
Cool. Good to know. Which was the solution that worked for you?

**Comment by tejaswankalluri** [comment]
> As a workaround you could also hardcode your values in the `docker-compose.yml` file. Change the `${TELOXIDE_TOKEN}` and `${BMS_APP_VERSION}` to your values and try proceeding.

This solution worked hardcoded the env variables in the docker-compose file
