### ISSUE TITLE
Send out a notification when seats in a specific theatre become available.

### ISSUE THREAD

**Issue by instaboy007** [abinpaul1/BookMyShow-ticket-notifier-telegram-bot#2]
"Send out a notification when seats in a specific theatre become available"
Is this feature available?

**Comment by abinpaul1** [comment]
Yes. The notification comes when seats first become available at a particular venue

**Comment by instaboy007** [comment]
> Yes. The notification comes when seats first become available at a particular venue

Okay Great Job.....Thanks
