### ISSUE TITLE
Found a Bug...

### ISSUE THREAD

**Issue by hiteshb** [abinpaul1/BookMyShow-ticket-notifier-telegram-bot#3]
![image](https://user-images.githubusercontent.com/60309998/200404652-3b81e7ec-f686-4573-bb31-5a33fd329a3d.png)
I tried to run it locally on 1 core 1 gb ram instance , at first it worked then immediately it got crashed.
I tried to change the value of rust_backtrace but it didn't work .
Can you fix it ?

**Comment by abinpaul1** [comment]
Have you set the token `export TELOXIDE_TOKEN=<Token from BotFather>`?

**Comment by hiteshb** [comment]
yes

**Comment by abinpaul1** [comment]
The error seems to be because the environment variable is missing.
can you check if it was set successfully. Maybe try `env | grep TELOXIDE` and ensure its present
